---
title: "Articles"
date: "`r Sys.Date()`"
author: "Ethen Liu"
output:
  rmdformats::readthedown:
    highlight: pygments
---

<style type="text/css">
p{ /* Normal  */
   font-size: 18px;
}
body{ /* Normal  */
   font-size: 18px;
}
td{  /* Table  */
   font-size: 14px;
}
h1{ /* Header 1 */
 font-size: 32px;
}
h2{ /* Header 2 */
 font-size: 26px;
}
h3{ /* Header 3 */
 font-size: 22px;
}
code.r{ /* Code block */
  font-size: 14px;
}
pre{ /* Code block */
  font-size: 14px
}
</style>

# Management

- The Pivotal Stories Every Startup Leader Should Be Able to Tell. [[First Round Review](http://firstround.com/review/the-pivotal-stories-every-startup-leader-should-be-able-to-tell/)]
- The Eisenhower Matrix Productivity Tool – As A Trello Board. [[Trello](http://blog.trello.com/eisenhower-matrix-productivity-tool-trello-board/?utm_source=newsletter&utm_medium=email&utm_campaign=july-2016-newsletter-2)]
- All About OKRs: How to Set Them, Achieve Them, and Track Them in Trello. [[Trello](http://blog.trello.com/okrs-set-achieve-track-trello/?utm_source=newsletter&utm_medium=email&utm_campaign=july-2016-newsletter-2)]
- The Single Most Important Skill for a Data Scientist. [[Mango Solution](http://www.mango-solutions.com/wp/2015/06/the-single-most-important-skill-for-a-data-scientist/)]
- How A/B Testing at LinkedIn, Wealthfront and eBay Made Me a Better Manager. [[First Round Review](http://firstround.com/review/how-a-b-testing-at-linkedin-wealthfront-and-ebay-made-me-a-better-manager/?ct=t(How_Does_Your_Leadership_Team_Rate_12_3_2015))]
- How Constraints Create Space for Innovation. [[linkedin pulse](https://www.linkedin.com/pulse/how-constraints-create-space-innovation-ash-maurya)]
- From Developer to Manager - PyCon 2016. [[Youtube](https://www.youtube.com/watch?v=lzBm0r8CxhY)]
- Reddit and Facebook Veteran On How to Troubleshoot Troublemakers. [[First Round Review](http://firstround.com/review/reddit-and-facebook-veteran-on-how-to-troubleshoot-troublemakers/?ct=t(How_Does_Your_Leadership_Team_Rate_12_3_2015))]
    - Hermits. Get them to collaborate with a team.
    - Nostalgia. Ask qualities that they missed most, and see if there're existing projects that could allow them to recapture that feeling.
    - Trend Chaser. Ask them why this is the route their going to take? The potential has to worth more than the expense of experimenting.
- Practical Frameworks for Beating Burnout [[First Round Review](http://firstround.com/review/practical-frameworks-for-beating-burnout/?ct=t(How_Does_Your_Leadership_Team_Rate_12_3_2015))]
- How to set goals: OKRs. [[Youtube](https://www.youtube.com/watch?v=mJB83EZtAjc)]
- Meetings that don’t suck. [[Youtube](https://www.youtube.com/watch?v=rU8nv38E0Qk)]


# Interviews and Careers

- 2016.12.27 | Crushed it! Landing a data science job. [[Blog](http://www.erinshellman.com/crushed-it-landing-a-data-science-job/)]
- 2016.12.27 | http://treycausey.com/data_science_interviews.html. [[Blog](http://treycausey.com/data_science_interviews.html)]
- What factors can increase your data science salary?. [[Springboard](https://www.springboard.com/blog/highest-data-scientist-salary-possible/?utm_campaign=Data%2BElixir&utm_medium=email&utm_source=Data_Elixir_90)]
- 5 Qualities You Need to Show in the Job Search. [[glassdoor](https://www.glassdoor.com/blog/qualities-show-off/?utm_source=newsletter&utm_medium=email&utm_content=Top5Jobs_US16&utm_campaign=May2016_US)]
    - Leadership ability. e.g. As a result of an incentive program I spearheaded, our sales team surpassed its quarterly sales goal by 15 percent.
    - Flexibility: keep track of times when you’ve had to assume multiple roles or responsibilities outside of your own.
    - Coachability: Be open and honest about where you fall short and how you’re actively improving on those shortcomings.
- Labels are for cans not for people. [[Facebook Videos](https://www.facebook.com/morokcom/videos/237500609921393/)]
- Land any job you want. [[blog](http://landanyjobyouwant.com/)]
- The career advice no one tells you. [[Quartz](http://qz.com/640112/the-career-advice-no-one-tells-you/)]
- Wanted in College Graduates: Tolerance for Ambiguity. [[Linkedin Pulse](https://www.linkedin.com/pulse/wanted-college-graduates-tolerance-ambiguity-jeff-selingo)]


# Analytics

- 2016.12.29 | Data Science Newsletter list. [[Medium](https://medium.com/blend-your-data/a-four-minute-read-big-data-and-data-science-newsletter-list-to-get-you-informed-on-anything-data-669d8e2c4b09#.2lukcelgg)]
- 2016.12.27 | Sharing Your Side Projects Online and Making Your Github the Best Résumé. [[Youtube](https://www.youtube.com/watch?v=uRul8QdYvqQ)]
    - Include a license to the project. there's even a [website](http://choosealicense.com/) that walks you through the copying and pasting process
    - [Binder](http://mybinder.org/) is a project that allows you to open up the jupyter notebook in a virual environment (specifying all the requirements in a requirements.txt file) and run it online without needing to download it
- 2016.12.24 | WHAT I LEARNED RECREATING ONE CHART USING 24 TOOLS. [[Blog](https://source.opennews.org/en-US/articles/what-i-learned-recreating-one-chart-using-24-tools/?utm_campaign=Data%2BElixir&utm_medium=web&utm_source=Data_Elixir_110)]
- The Most Practical Big Data Use Cases Of 2016. [[Forbes](http://www.forbes.com/sites/bernardmarr/2016/08/25/the-most-practical-big-data-use-cases-of-2016/?inf_contact_key=851fbbc780fa7ed1332d888a227af9856e3f8925ffc7f91b9e0f03dfa5587a98#4c9dd6697533)]
    - Sales, Manufacture, Health Care
- Cameron Davidson Pilon: Mistakes I've Made. [[Youtube](https://www.youtube.com/watch?v=VWtsTIbFXxA)]
    - Always be aware of the sample sizes when computing aggregated data.
    - Correlated data can lead to misinterpretation of the results.
- Data Science: Beyond the Kaggle. [[Blog](http://datawrangl.com/2016/05/15/data-science-beyond-the-kaggle/)]
- Mentality for hackathons. [[Medium](https://medium.com/data-engineering/modeling-madly-8b2c72eb52be#.q9ly8hxq2)]
- The top 5 habits of a professional data scientist. [[OREILLY](https://www.oreilly.com/learning/theres-nothing-magical-about-learning-data-science?imm_mid=0e6c5a&cmp=em-data-na-na-newsltr_20160817)]
- The Inconvenient Truth About Data Science. [[Linkedin Pulse](https://www.linkedin.com/pulse/inconvenient-truth-data-science-kamil-bartocha)]
- Data science tips from reddit
The Top Five Data Science Tips From r/DataScience. [[Blog](http://www.datadependence.com/2016/07/best-data-science-tips-reddit/?utm_content=buffer076f2&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)]
- Data scientists mostly just do arithmetic and that’s a good thing. [[Blog](https://m.signalvnoise.com/data-scientists-mostly-just-do-arithmetic-and-that-s-a-good-thing-c6371885f7f6#.dly3ud86c)]
- The one machine learning concept you need to know. [[Blog](http://www.sharpsightlabs.com/one-concept-machine-learning/)]
    - When you’re doing machine learning (specifically, supervised learning), you’re essentially using computational techniques to find the underlying relationships between the input and the output.
- Check Yourself: 5 Things You Should Know About Data Science (Author Note). [[Blog](http://analyticsmadeskeezy.com/2012/11/05/check-yo-self-5-things-you-should-know-about-data-science-author-note/)]
- Statistics for Hackers - PyCon 2016 [[Youtube]](https://www.youtube.com/watch?v=-7I7MWTX0gA)
- The questions to ask before implementing any big data strategy. [[the guardian](http://www.theguardian.com/sap-partner-zone/2016/apr/28/questions-before-implementing-big-data-strategy)]
    - What is the biggest challenge my business is facing right now and what do you do and don't know about your customer. and see how you can tweak your current strategy to make it more customer and data-driven.
- Data Pitfalls —the Startup Edition. [[Medium](https://medium.com/@mrogati/data-pitfalls-the-startup-edition-fe1eebcc39da#.si84k3dss)]
- 6 Best Practices for implementing In-store Personalization in 2015. [[beaconstac](http://blog.beaconstac.com/2015/07/6-best-practices-for-implementing-in-store-personalization-in-2015/)]
    - Activating purchases: Say, Laura purchased a lemon yellow shirt at your retail store outlet located in New York. Now, a week later, you can send out an offer (via email and through a mobile app push notification) on a brown trouser that’ll go along with the shirt. The offer can be redeemed on your online store or a physical outlet.
    - Pushing shoppers forward in the buying path: Say the same customer, Laura, actually went on to browse handbags online after she received the email offer. As soon she walks into your physical retail store, you can send a  notification through her mobile app, asking if she wishes to touch and feel the handbags that she browsed online.
- How Big Data is changing e-commerce for good [[Future of Commerce](http://www.the-future-of-commerce.com/2014/12/15/how-big-data-is-changing-e-commerce-for-good/)]
    - The top three things that retailers needs to know: how effective their pricing is, when shoppers are most active and what items they buy together (promoting products that shoppers often buy together can boost your average order value and help products move more quickly). 
- Do data scientists need to be domain experts to deliver good analytics? [[Data Science Central](http://www.datasciencecentral.com/profiles/blogs/do-data-scientists-need-to-be-domain-experts-to-deliver-good)]
    - Often, good data scientists become subject experts just by playing with the data and asking questions to domain experts about the data anomalies. Through their questioning they will cross-pollinate the subject matter experts so the team as a whole is stronger.
    - Machine learning brings a fresh perspective that leads to new insights and no prior domain knowledge can potentially be advantageous, especially in overcoming long standing domain bias.
- Using Machine Learning to Predict Customer Behaviour [[Data Science Central](http://www.datasciencecentral.com/profiles/blogs/using-machine-learning-to-predict-customer-behaviour)]
    - Used with Complaints Management, Customer Upsell and Customer Retention. Questions include How to anticipate and manage the dissatisfaction of the customers?', 'How to sell more and better to existing customers?' and 'How to keep the most profitable customers at an appropriate cost?'
    - Action: You identify a target behaviour, in our case, it is a specific customer action, like filing a complaint/not filing a complaint, accepting or rejecting an upsell offer, cancelling / not cancelling a service. Then perform supervised learning
- Doing Data Science Right — Your Most Common Questions Answered. [[Review](http://firstround.com/review/doing-data-science-right-your-most-common-questions-answered/?imm_mid=0e29cf&cmp=em-data-na-na-newsltr_20160413)]
- Principles of good data analytics. [[blog](http://www.gregreda.com/2014/03/23/principles-of-good-data-analysis/)] 
- Why I Ditched My Fitbit and What This Means for Analytics. [[Data Science Central](http://www.datasciencecentral.com/profiles/blogs/why-i-ditched-my-fitbit-and-what-this-means-for-analytics)]
- Know the Difference between Customer Service and Customer Experience. [[Harvard Business Review](https://hbr.org/sponsored/2016/03/know-the-difference-between-customer-service-and-customer-experience?utm_source=twitter&utm_medium=social&utm_campaign=harvardbiz)]
- Two articles about saying no to p-values. [[R-bloggers](http://www.r-bloggers.com/after-150-years-the-asa-says-no-to-p-values/)][[R-bloggers](http://www.r-bloggers.com/its-not-the-p-values-fault-reflections-on-the-recent-asa-statement-relevant-r-resources/)]
- The 9 Best Marketing And Sales Analytics You Should Know About.[[Data Science Central](http://www.datasciencecentral.com/profiles/blogs/the-9-best-marketing-and-sales-analytics-you-should-know-about)]
- Cohort analysis. [[Youtube](https://www.youtube.com/watch?v=NyhVdGmnh0I)]
- Ted Talk : How to use data to make a hit TV show. [[Ted](http://www.ted.com/talks/sebastian_wernicke_how_to_use_data_to_make_a_hit_tv_show?utm_campaign=social&utm_medium=referral&utm_source=facebook.com&utm_content=talk&utm_term=technology)]


# Business

- The New 'Must Haves' for Mobile Apps to Succeed Today. [[First Round Review](http://firstround.com/review/the-new-must-haves-for-mobile-apps-to-succeed-today/)]
- 'Amazon is not your friend'. [[Linkedin](https://www.linkedin.com/pulse/amazon-your-friend-caroline-fairchild)]
    - The only way to survive is to build a brand that can grow without Amazon’s distribution.
    - Amazon hasn’t proven that it can build inspirational brands. While they have mastered the ability to get customers commodity products, no one goes to Amazon to discover something they didn’t already know about.
- Facebook is the new Excel. [[blog](http://alexmuir.com/facebook-is-the-new-excel)]
- We need companies to start innovating instead of imitating success stories. [[Hustle](http://thehustle.co/snapchat-vs-spacex-battle-of-the-imitators-and-innovators)]
- My 4+ Years At Uber Taught Me These Key Lessons. 1. May the supply be with you ; 2. Don't listen, show them. [[Linkedin](https://www.linkedin.com/pulse/three-things-i-learned-during-4-years-uber-michael-pao)]


# Learn Data Science

- The Mathematics of Machine Learning. [[Blog]](http://datascience-africa.org/2016/07/mathematics-machine-learning/)
- The MBA Data Science Toolkit: 8 resources to go from the spreadsheet to the command line. [[Medium](https://medium.com/@dmca/the-mba-data-science-toolkit-8-resources-to-go-from-the-spreadsheet-to-the-command-line-cbb59ea82144#.pjph91n3m)]
